/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ball_ex_MainActivity */

#ifndef _Included_com_example_ball_ex_MainActivity
#define _Included_com_example_ball_ex_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_ball_ex_MainActivity_CAMERA_PERMISSION_REQUEST_CODE
#define com_example_ball_ex_MainActivity_CAMERA_PERMISSION_REQUEST_CODE 200L
#ifdef __cplusplus
}
#endif
#endif
